#!/bin/sh

branchName=$(~/scripts/GitBranchName.sh)

firstLine=$(head -n1 $1)

echo "BranchName: $branchName"

if [ -z "$firstLine"  ] ;then #Check that this is not an amend by checking that the first line is empty
    sed -i "1s/^/\n$branchName #time m \n/" $1 #Insert branch name at the start of the commit message file
fi
